"""
PDF session report generation — turns a session_store report dict into a
downloadable PDF (chart + timeline table), returned as raw bytes.
"""

import io
from datetime import datetime

import matplotlib
matplotlib.use("Agg")  # headless: no display/Tk backend available on a server
import matplotlib.pyplot as plt

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    Image as RLImage,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

VERDICT_COLORS = {
    "SAFE TO DRIVE": colors.HexColor("#22c55e"),
    "TAKE A BREAK": colors.HexColor("#eab308"),
    "STOP NOW": colors.HexColor("#ef4444"),
    "NO DATA": colors.HexColor("#6b7280"),
}


def _render_score_chart(timeline: list) -> io.BytesIO:
    scores = [entry["safety_score"] for entry in timeline]
    alert_idx = [i for i, e in enumerate(timeline) if e["alert_triggered"]]

    fig, ax = plt.subplots(figsize=(6.5, 2.6), dpi=150)
    ax.axhspan(80, 100, color="#22c55e", alpha=0.12)
    ax.axhspan(50, 80, color="#eab308", alpha=0.12)
    ax.axhspan(0, 50, color="#ef4444", alpha=0.12)
    ax.plot(range(len(scores)), scores, color="#4f46e5", linewidth=1.8)
    if alert_idx:
        ax.scatter(alert_idx, [scores[i] for i in alert_idx], color="#ef4444", s=22, zorder=3)
    ax.set_ylim(0, 100)
    ax.set_xlim(0, max(len(scores) - 1, 1))
    ax.set_ylabel("Safety score")
    ax.set_xlabel("Chunk #")
    fig.tight_layout()

    buf = io.BytesIO()
    fig.savefig(buf, format="png")
    plt.close(fig)
    buf.seek(0)
    return buf


def generate_session_pdf(report: dict) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=letter, topMargin=0.6 * inch, bottomMargin=0.6 * inch)
    styles = getSampleStyleSheet()
    verdict_color = VERDICT_COLORS.get(report["overall_verdict"], colors.black)

    elements = []
    elements.append(Paragraph("Driver Safety Monitor — Session Report", styles["Title"]))
    elements.append(Spacer(1, 4))
    elements.append(Paragraph(
        f"Generated {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')} &middot; "
        f"Session {report['session_id']} &middot; Duration {report['duration_seconds']}s",
        styles["Normal"],
    ))
    elements.append(Spacer(1, 14))

    verdict_style = ParagraphStyle(
        "Verdict", parent=styles["Title"], fontSize=22, textColor=verdict_color,
    )
    elements.append(Paragraph(report["overall_verdict"], verdict_style))
    elements.append(Paragraph(
        f"Average safety score: {report['average_safety_score']} / 100 &middot; "
        f"Dominant state: {report['dominant_state']} &middot; "
        f"{len(report['risk_events'])} risk event(s)",
        styles["Normal"],
    ))
    elements.append(Spacer(1, 14))

    if report["timeline"]:
        chart_buf = _render_score_chart(report["timeline"])
        elements.append(RLImage(chart_buf, width=6.5 * inch, height=2.6 * inch))
        elements.append(Spacer(1, 14))

    table_data = [["Time", "State", "Confidence", "Safety score"]]
    risk_rows = set()
    for i, entry in enumerate(report["timeline"], start=1):
        table_data.append([
            entry["timestamp"].split("T")[-1].split("+")[0][:8],
            entry["state"],
            f"{entry['confidence']:.1f}%",
            str(entry["safety_score"]),
        ])
        if entry["alert_triggered"]:
            risk_rows.add(i)

    if len(table_data) > 1:
        table = Table(
            table_data, hAlign="LEFT",
            colWidths=[1.4 * inch, 1.6 * inch, 1.6 * inch, 1.6 * inch],
        )
        style = [
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1f2937")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#d1d5db")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f3f4f6")]),
        ]
        for row in risk_rows:
            style.append(("BACKGROUND", (0, row), (-1, row), colors.HexColor("#fecaca")))
        table.setStyle(TableStyle(style))
        elements.append(table)
    else:
        elements.append(Paragraph("No chunks were recorded in this session.", styles["Normal"]))

    elements.append(Spacer(1, 24))
    elements.append(Paragraph("Generated by Driver Safety Monitor", styles["Italic"]))

    doc.build(elements)
    return buf.getvalue()
